import { NextResponse } from "next/server";
import { IncidentAnalysis } from "@/lib/schemas/incident";
import { ToolCallRecord } from "@/lib/tools/executor";
import { AgentContribution } from "@/lib/asi/analyze";

interface ReportRequest {
  incident: IncidentAnalysis;
  toolCalls: ToolCallRecord[];
  agentContributions: AgentContribution[];
}

function generateMarkdownReport(data: ReportRequest): string {
  const { incident, toolCalls, agentContributions } = data;
  const severityEmoji: Record<string, string> = {
    critical: "🔴",
    high: "🟠",
    medium: "🟡",
    low: "🟢",
    info: "🔵",
  };

  const lines: string[] = [
    `# Incident Report: ${incident.title}`,
    "",
    `**Incident ID:** ${incident.incident_id}`,
    `**Timestamp:** ${new Date(incident.timestamp).toLocaleString()}`,
    `**Severity:** ${severityEmoji[incident.severity] || ""} ${incident.severity.toUpperCase()}`,
    `**Category:** ${incident.category.replace(/_/g, " ")}`,
    `**Confidence:** ${(incident.confidence * 100).toFixed(0)}%`,
    "",
    "---",
    "",
    "## Executive Summary",
    "",
    incident.summary,
    "",
    "## Probable Root Cause",
    "",
    incident.probable_root_cause,
    "",
    "## Evidence",
    "",
    "| Source | Event | Time | Detail | Relevance |",
    "|--------|-------|------|--------|-----------|",
    ...incident.evidence.map(
      (e) =>
        `| ${e.source} | ${e.event_type} | ${new Date(e.timestamp).toLocaleTimeString()} | ${e.detail} | ${e.relevance} |`
    ),
    "",
    "## Affected Assets",
    "",
    ...incident.affected_assets.map((a) => `- ${a}`),
    "",
    "## Recommended Actions",
    "",
    ...incident.immediate_actions.map(
      (a, i) =>
        `${i + 1}. **[${a.urgency.toUpperCase()}]** ${a.action} — Target: ${a.target}\n   - Impact: ${a.estimated_impact}`
    ),
    "",
    "## Escalation Path",
    "",
    ...incident.escalation_path.map((p, i) => `${i + 1}. ${p}`),
    "",
    "## Business / Safety Impact",
    "",
    incident.business_or_safety_impact,
    "",
  ];

  if ((incident.alternative_hypotheses?.length ?? 0) > 0) {
    lines.push("## Alternative Hypotheses", "");
    for (const h of incident.alternative_hypotheses) {
      if (typeof h === "string") {
        lines.push(`- ${h}`, "");
      } else {
        const conf = h.confidence != null ? ` (${(h.confidence * 100).toFixed(0)}% confidence)` : "";
        lines.push(`### ${h.hypothesis ?? "Unknown"}${conf}`, "");
        if (h.supporting_evidence?.length) {
          lines.push("**Supporting evidence:**", ...h.supporting_evidence.map((e) => `- ${e}`), "");
        }
        if (h.contradicting_evidence?.length) {
          lines.push("**Contradicting evidence:**", ...h.contradicting_evidence.map((e) => `- ${e}`), "");
        }
      }
    }
  }

  if (agentContributions.length > 0) {
    lines.push("## Specialist Agent Findings", "");
    for (const agent of agentContributions) {
      lines.push(
        `### ${agent.role}`,
        "",
        agent.analysis,
        "",
        "**Key Recommendations:**",
        ...agent.recommendations.map((r) => `- ${r}`),
        ""
      );
    }
  }

  if (toolCalls.length > 0) {
    lines.push("## Tool Calls Executed", "");
    for (const tc of toolCalls) {
      lines.push(
        `### ${tc.name}`,
        "",
        `**Arguments:** \`${JSON.stringify(tc.arguments)}\``,
        "",
        `**Result:** \`${JSON.stringify(tc.result).slice(0, 500)}\``,
        ""
      );
    }
  }

  lines.push(
    "---",
    "",
    `*Report generated by SentinelMesh at ${new Date().toISOString()}*`,
    "",
    "*Powered by ASI-1 reasoning engine*"
  );

  return lines.join("\n");
}

export async function POST(request: Request) {
  try {
    const body: ReportRequest = await request.json();

    if (!body.incident) {
      return NextResponse.json(
        { error: "incident data is required" },
        { status: 400 }
      );
    }

    const markdown = generateMarkdownReport(body);

    return NextResponse.json({ markdown });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Report generation failed";
    console.error("Report error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
